:sparkles: feat: proven section added
interest-protocol/suitears-lp pull request #5
Opened 2023-12-12 16:06 UTC by atilasousa

2023-12-12 20:08 UTC, MarioBatalha requested changes

2023-12-12 20:08 UTC, MarioBatalha commented on components/svg/moveBit.tsx
> +      fill="#1B1B1F"
currentColor

2023-12-12 20:08 UTC, MarioBatalha commented on components/svg/moveBit.tsx
> +      fill="#1B1B1F"
And we have this color in UI

2023-12-12 20:08 UTC, MarioBatalha commented on components/svg/moveBit.tsx
> +      fill="#1B1B1F"
currentColor

2023-12-12 20:08 UTC, MarioBatalha commented on views/institutional/components/proven/index.tsx
> +            display="flex"
is missing border in this card

2023-12-13 01:46 UTC, MarioBatalha approved these changes

2023-12-13 02:07 UTC, MarioBatalha commented on views/institutional/components/proven/audit-card.tsx
> +      justifyContent="space-between"
This card doesn't looks like the UI on figma

2023-12-13 02:14 UTC, MarioBatalha requested changes

2023-12-13 02:14 UTC, MarioBatalha commented on views/institutional/components/proven/audit-card.tsx
> +      border={`0.063rem solid ${theme.colors.onPrimary}`}
This card doesn't looks like the UI on figma, I'm not sure if its border or box shadow but is missing something.

2023-12-13 02:20 UTC, MarioBatalha requested changes

2023-12-13 02:20 UTC, MarioBatalha commented on views/institutional/components/proven/audit-card.tsx
> +      background={`linear-gradient(36deg, ${theme.colors.onPrimary} 2.01%, rgba(255, 255, 255, 0.16) 98.41%)`}
Also check the card bg color

2023-12-14 01:16 UTC, KipandaJr requested changes

2023-12-14 01:16 UTC, KipandaJr commented on views/institutional/components/proven/index.tsx
> +        <Typography size="medium" fontFamily="Satoshi" variant="display">
this title need a `fontWeight: 700`

2023-12-14 01:16 UTC, KipandaJr commented on views/institutional/components/proven/index.tsx
> +          size="medium"
this description need a `size: large`

2023-12-14 01:16 UTC, KipandaJr commented on views/institutional/components/proven/index.tsx
> +          {`Our team has a track record of successfully deploying and managing
remove the `{'` its a string

2023-12-14 01:16 UTC, KipandaJr commented on views/institutional/components/proven/audit-card.tsx
> +        <Typography
this typography are wrong according figma... `variant='body'` and `size='large'`

2023-12-14 01:16 UTC, KipandaJr commented on components/layout/index.tsx
> +    backgroundImage="linear-gradient(0deg, #EEEA, #EEEA), url('/img/noise.png')"
convert this image `noise.png` to `noise.webp`

2023-12-14 01:16 UTC, KipandaJr commented on components/svg/index.ts
> +export { default as MoveBitSVG } from './moveBit';
change `moveBit` to `move-bit`

2023-12-14 01:16 UTC, KipandaJr commented on components/svg/moveBit.tsx
> +const MoveBit: FC<SVGProps> = ({ maxWidth, maxHeight, ...props }) => (
change `moveBit` to `move-bit`

2023-12-14 07:33 UTC, atilasousa commented on views/institutional/components/proven/index.tsx
> +          {`Our team has a track record of successfully deploying and managing
It's must go this way because it won't pass on linter

2023-12-14 15:00 UTC, MarioBatalha approved these changes

2023-12-14 20:15 UTC, KipandaJr requested changes

2023-12-14 20:15 UTC, KipandaJr commented on views/institutional/components/proven/index.tsx
On mobile the card r wrong/diff to figma

2023-12-19 21:08 UTC, KipandaJr requested changes

2023-12-19 21:08 UTC, KipandaJr commented on views/institutional/components/proven/audit-card.tsx
> +            fontFamily="Satoshi"
check if this pros `fontWeight, lineHeight and fontFamily` r diff to we have on ui-kit variant... because i think u r a replace this value...

2023-12-19 21:08 UTC, KipandaJr commented on views/institutional/components/proven/audit-card.tsx
> +          px={0}
pass this like `string`

2023-12-19 21:08 UTC, KipandaJr commented on views/institutional/components/proven/audit-card.tsx
> +          <Typography variant="body" size="medium" fontFamily="Proto">
this `fontFamily` r necessary?

2023-12-19 21:08 UTC, KipandaJr commented on views/institutional/components/proven/index.tsx
> +          fontFamily="Satoshi"
check if this props r not to do a replace

2023-12-19 21:08 UTC, KipandaJr commented on views/institutional/components/proven/index.tsx
> +          Sui hackathons.`}
remove this `{'`

2023-12-19 23:20 UTC, MarioBatalha approved these changes

2023-12-21 17:18 UTC, git-marcopitra approved these changes

2023-12-21 17:19 UTC, merged