:sparkles:  add how it works section
interest-protocol/suitears-lp pull request #7
Opened 2023-12-13 17:09 UTC by MarioBatalha

2023-12-13 21:55 UTC, atilasousa commented on views/institutional/components/feature/feature-header.tsx
> +    <Tag variant="outline" size="medium" width="max-content" mb="2rem">
check the ui kit for this mb size

2023-12-13 21:55 UTC, atilasousa commented on views/institutional/components/feature/index.tsx
> +    width="100vw"
pleasee, check if it's really necessary this width

2023-12-13 21:55 UTC, atilasousa commented on views/institutional/components/feature/feature-header.tsx
> +      mb="1rem"
check this size in the ui kit

2023-12-13 21:55 UTC, atilasousa commented on views/institutional/components/feature/feature-description.tsx
> +      lineHeight="4rem"
check this size in the ui kit

2023-12-15 01:58 UTC, KipandaJr requested changes
your approach of using the backgrounds as svg and then rendering them on the site isn't going to work in all cases, I suggest you think about it differently, or say something so we can sort it out in the `war-room` @MarioBatalha

2023-12-15 09:02 UTC, MarioBatalha commented
> your approach of using the backgrounds as svg and then rendering them on the site isn't going to work in all cases, I suggest you think about it differently, or say something so we can sort it out in the `war-room` @MarioBatalha

Image in webp format reduce image quality

2023-12-15 20:00 UTC, KipandaJr requested changes
when u free tell me to do this on pair programming in war-room.

2023-12-19 23:16 UTC, git-marcopitra requested changes

2023-12-19 23:16 UTC, git-marcopitra commented on views/institutional/index.tsx
>  import { Benefits, Hero } from './components';
export it on the Baril, to be like this other sections

2023-12-19 23:16 UTC, git-marcopitra commented on views/institutional/components/feature/feature-header.tsx
> +    py={['2rem', '2rem', '2rem', '4rem']}
change this values to theme keys

2023-12-20 01:09 UTC, KipandaJr requested changes
<img width="1045" alt="image" src="https://github.com/interest-protocol/suitears-lp/assets/34079870/40545b5b-9f2f-42e3-9264-5f80fd390c10">

the `width` is diff in compare to fix


<img width="976" alt="image" src="https://github.com/interest-protocol/suitears-lp/assets/34079870/8274f537-c26f-40ff-9019-b3363cfd43c7">
the space between image and text r so long

2023-12-20 01:09 UTC, KipandaJr commented on views/institutional/components/feature/feature-header.tsx
> +    py={['3xl', '3xl', '3xl', '4rem']}
`4rem` is `8xl`

2023-12-20 01:09 UTC, KipandaJr commented on views/institutional/components/feature/feature-header.tsx
> +      fontFamily="Satoshi"
u cant put this props `fontFamily`

2023-12-21 17:47 UTC, KipandaJr requested changes
The mobile version are diff plz check this too

2023-12-21 17:47 UTC, KipandaJr commented on components/svg/svg.types.ts
> +  maxHeight?: string;
Why u change this sir ?

2023-12-21 17:47 UTC, KipandaJr commented on views/institutional/components/feature/feature-card.tsx
> +        bg="#0053DB"
this Colors dosent exist on `ui-kit`

2023-12-21 17:47 UTC, KipandaJr commented on views/institutional/components/feature/index.tsx
> +    />
Build one object to map this

2023-12-21 17:47 UTC, KipandaJr commented on public/img/features.webp
this image r necessary?

2023-12-21 17:50 UTC, merged